// <auto-generated />
namespace Domen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addInstaIdLONG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addInstaIdLONG));
        
        string IMigrationMetadata.Id
        {
            get { return "201607082033478_add InstaId(LONG)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
